import { useEffect } from "react";
import { PortfolioData } from "../types";
import { processAutoGeneratedEntries } from "../lib/utils";

export function useAutoScheduler(
  data: PortfolioData,
  updateData: (data: Partial<PortfolioData>) => void,
) {
  useEffect(() => {
    const scheduled = processAutoGeneratedEntries(data);
    const currentSnapshot = JSON.stringify({
      expenses: data.expenses,
      investments: data.investments,
      recurringRules: data.recurringRules,
    });
    const nextSnapshot = JSON.stringify({
      expenses: scheduled.expenses,
      investments: scheduled.investments,
      recurringRules: scheduled.recurringRules,
    });

    if (currentSnapshot !== nextSnapshot) {
      updateData(scheduled);
    }
  }, [data, updateData]);
}
