export type AccountType = "Savings" | "Current" | "Salary" | "Cash";

export interface BankAccount {
  id: string;
  bankName: string;
  accountType: AccountType;
  accountNumber: string;
  balance: number;
  notes?: string;
  isCash?: boolean;
}

export type InvestmentStatus = "Active" | "Paused" | "Stopped";
export type MFCategory = "Equity" | "Debt" | "Hybrid" | "ELSS" | "Index";

export interface LumpsumEntry {
  id: string;
  date: string;
  amount: number;
}

export interface SIPDetails {
  monthlyAmount: number;
  startDate: string;
  status: InvestmentStatus;
  stoppedDate?: string;
  totalSIPInvested?: number;
}

export interface MutualFund {
  id: string;
  fundName: string;
  amc: string;
  category: MFCategory;
  sipDetails?: SIPDetails;
  lumpsumEntries: LumpsumEntry[];
  currentValue: number;
}

export type BrokerType = "Groww" | "Zerodha" | "Upstox" | "Other";

export interface Stock {
  id: string;
  companyName: string;
  ticker: string;
  quantity: number;
  avgBuyPrice: number;
  currentPrice: number;
}

export interface StockPortfolio {
  id: string;
  name: string;
  ownerName: string;
  broker: BrokerType;
  holdings: Stock[];
}

export interface FixedDeposit {
  id: string;
  bankName: string;
  principal: number;
  interestRate: number;
  startDate: string;
  maturityDate: string;
}

export interface RecurringDeposit {
  id: string;
  bankName: string;
  monthlyDeposit: number;
  interestRate: number;
  startDate: string;
  maturityDate: string;
}

export type IncomeSource = "Salary" | "Freelance" | "Dividends" | "Interest" | "Rental" | "Other";

export interface IncomeEntry {
  id: string;
  date: string;
  source: IncomeSource;
  amount: number;
  description?: string;
  toAccountId: string | null;
  toAccountName: string | null;
}

export type ExpenseCategory =
  | "Food"
  | "Rent"
  | "EMI"
  | "Utilities"
  | "Entertainment"
  | "Medical"
  | "Travel"
  | "Investment"
  | "Beauty"
  | "Social Life"
  | "Transport"
  | "Other";

export type PaymentMethod = "Cash" | "UPI" | "Card" | "Net Banking" | "NEFT/IMPS" | "Cheque";

export interface ExpenseEntry {
  id: string;
  date: string;
  category: ExpenseCategory;
  amount: number;
  fromAccountId: string | null;
  fromAccountName: string | null;
  paymentMethod: PaymentMethod;
  description?: string;
  isAutoGenerated?: boolean;
  recurringRuleId?: string;
}

export interface TransferEntry {
  id: string;
  date: string;
  amount: number;
  fromAccountId: string;
  fromAccountName: string;
  toAccountId: string;
  toAccountName: string;
  description?: string;
  fees: number;
}

export type LoanType = "Home" | "Personal" | "Vehicle" | "Education" | "Credit Card" | "Other";

export interface Loan {
  id: string;
  lenderName: string;
  loanType: LoanType;
  principalAmount: number;
  outstandingBalance: number;
  emiAmount: number;
  interestRate: number;
  emiDate: number;
  startDate: string;
  endDate: string;
}

export type RecurringFrequency =
  | "daily"
  | "weekdays"
  | "weekends"
  | "weekly"
  | "biweekly"
  | "every4weeks"
  | "monthly"
  | "endofmonth"
  | "every2months"
  | "every3months"
  | "every4months"
  | "every6months"
  | "yearly";

export interface RecurringRule {
  id: string;
  name: string;
  amount: number;
  category: ExpenseCategory;
  paymentMethod: PaymentMethod;
  fromAccountId: string | null;
  fromAccountName: string | null;
  description?: string;
  frequency: RecurringFrequency;
  dayOfMonth?: number;
  dayOfWeek?: number;
  monthOfYear?: number;
  startDate: string;
  endDate: string | null;
  isActive: boolean;
  lastProcessedMonth?: string;
}

export type YearViewMode = "calendar" | "financial";

export interface PortfolioData {
  bankAccounts: BankAccount[];
  transfers: TransferEntry[];
  investments: {
    mutualFunds: MutualFund[];
    stockPortfolios: StockPortfolio[];
    fd: FixedDeposit[];
    rd: RecurringDeposit[];
  };
  income: IncomeEntry[];
  expenses: ExpenseEntry[];
  loans: Loan[];
  recurringRules: RecurringRule[];
  settings: {
    monthlyBudget: number;
    yearView: YearViewMode;
  };
}
